<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: third_party/errors/errors.proto

namespace Xhtkyy\IdGenerator\Grpc\GPBMetadata\Kratos\Errors;

class Errors
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ã
third_party/errors/errors.protoerrors google/protobuf/descriptor.protoBµ
com.github.kratos.errorsPZ,github.com/go-kratos/kratos/v2/errors;errors¢KratosErrors %Xhtkyy\\IdGenerator\\Grpc\\Kratos\\Errors‚1Xhtkyy\\IdGenerator\\Grpc\\GPBMetadata\\Kratos\\Errorsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

