<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global/v1/id.proto

namespace Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>global.v1.ID.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .global.v1.ID payload = 1;</code>
     */
    private $payload;
    /**
     * Generated from protobuf field <code>.global.v1.ID.Format format = 2;</code>
     */
    protected $format = 0;
    /**
     * 所属的名字空间，直接返回
     *
     * Generated from protobuf field <code>string namespace = 3 [(.validate.rules) = {</code>
     */
    protected $namespace = '';
    /**
     * 域，直接返回
     *
     * Generated from protobuf field <code>string domain = 4 [(.validate.rules) = {</code>
     */
    protected $domain = '';
    /**
     * 时间戳
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 5;</code>
     */
    protected $timestamp = null;
    /**
     * 额外的数据，直接返回，如果请求时没有提供则不返回
     *
     * Generated from protobuf field <code>int64 extra = 6;</code>
     */
    protected $extra = 0;
    /**
     * Generated from protobuf field <code>.global.v1.ID.Secret secret = 7;</code>
     */
    protected $secret = null;
    /**
     * Generated from protobuf field <code>.global.v1.ID.Type type = 8;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID[]|\Google\Protobuf\Internal\RepeatedField $payload
     *     @type int $format
     *     @type string $namespace
     *           所属的名字空间，直接返回
     *     @type string $domain
     *           域，直接返回
     *     @type \Google\Protobuf\Timestamp $timestamp
     *           时间戳
     *     @type int|string $extra
     *           额外的数据，直接返回，如果请求时没有提供则不返回
     *     @type \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Secret $secret
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \Xhtkyy\IdGenerator\Grpc\GPBMetadata\v1\Id::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .global.v1.ID payload = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>repeated .global.v1.ID payload = 1;</code>
     * @param \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPayload($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID::class);
        $this->payload = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.global.v1.ID.Format format = 2;</code>
     * @return int
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>.global.v1.ID.Format format = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkEnum($var, \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Format::class);
        $this->format = $var;

        return $this;
    }

    /**
     * 所属的名字空间，直接返回
     *
     * Generated from protobuf field <code>string namespace = 3 [(.validate.rules) = {</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * 所属的名字空间，直接返回
     *
     * Generated from protobuf field <code>string namespace = 3 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * 域，直接返回
     *
     * Generated from protobuf field <code>string domain = 4 [(.validate.rules) = {</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * 域，直接返回
     *
     * Generated from protobuf field <code>string domain = 4 [(.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 5;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * 时间戳
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * 额外的数据，直接返回，如果请求时没有提供则不返回
     *
     * Generated from protobuf field <code>int64 extra = 6;</code>
     * @return int|string
     */
    public function getExtra()
    {
        return $this->extra;
    }

    /**
     * 额外的数据，直接返回，如果请求时没有提供则不返回
     *
     * Generated from protobuf field <code>int64 extra = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExtra($var)
    {
        GPBUtil::checkInt64($var);
        $this->extra = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.global.v1.ID.Secret secret = 7;</code>
     * @return \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Secret|null
     */
    public function getSecret()
    {
        return $this->secret;
    }

    public function hasSecret()
    {
        return isset($this->secret);
    }

    public function clearSecret()
    {
        unset($this->secret);
    }

    /**
     * Generated from protobuf field <code>.global.v1.ID.Secret secret = 7;</code>
     * @param \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Secret $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkMessage($var, \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Secret::class);
        $this->secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.global.v1.ID.Type type = 8;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.global.v1.ID.Type type = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Type::class);
        $this->type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Response::class, \Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID_Response::class);

