<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global/v1/id.proto

namespace Xhtkyy\IdGenerator\Grpc\Global\v1\Id;

if (false) {
    /**
     * This class is deprecated. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Error instead.
     * @deprecated
     */
    class ID_Error {}
}
class_exists(ID\Error::class);
@trigger_error('Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID_Error is deprecated and will be removed in the next major release. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Error instead', E_USER_DEPRECATED);

