<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global/v1/id.proto

namespace Xhtkyy\IdGenerator\Grpc\Global\v1\Id;

if (false) {
    /**
     * This class is deprecated. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Format instead.
     * @deprecated
     */
    class ID_Format {}
}
class_exists(ID\Format::class);
@trigger_error('Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID_Format is deprecated and will be removed in the next major release. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Format instead', E_USER_DEPRECATED);

