<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global/v1/id.proto

namespace Xhtkyy\IdGenerator\Grpc\Global\v1\Id;

if (false) {
    /**
     * This class is deprecated. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Response instead.
     * @deprecated
     */
    class ID_Response {}
}
class_exists(ID\Response::class);
@trigger_error('Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID_Response is deprecated and will be removed in the next major release. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Response instead', E_USER_DEPRECATED);

