<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: global/v1/id.proto

namespace Xhtkyy\IdGenerator\Grpc\Global\v1\Id;

if (false) {
    /**
     * This class is deprecated. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Secret instead.
     * @deprecated
     */
    class ID_Secret {}
}
class_exists(ID\Secret::class);
@trigger_error('Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID_Secret is deprecated and will be removed in the next major release. Use Xhtkyy\IdGenerator\Grpc\Global\v1\Id\ID\Secret instead', E_USER_DEPRECATED);

